---
- hosts: servers
  remote_user: candidate
  become: yes
  tasks:
  - name: Copy Cronjob
    copy:
      dest: /usr/local/bin/tracing.sh
      src: scripts/tracing.sh
      mode: 0755
  - name: Install Cronjob
    cron:
      name: "load"
      minute: "*"
      hour: "*"
      job: "/usr/local/bin/tracing.sh"
  - name: Ensure /shareddir exists
    file: 
      path: /shareddir
      state: directory
  - name: Mount NFS
    mount:
      fstype: nfs
      opts: defaults
      dump: '0'
      passno: '0'
      state: mounted 
      name: "/shareddir"
      src: "192.168.19.212:/nfs/data"
